package SDGSweden;

import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author fredde
 */
public class LaggTillAnstalld extends javax.swing.JFrame {
    private InfDB idb;
    private String aid;
    /**
     * Creates new form LaggTillAnstalld
     */
    public LaggTillAnstalld(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        
    jfornamn.setText("");
    jefternamn.setText("");
    jadress.setText("");
    jemail.setText("");
    jtelefon.setText("");
    janstallningsdatum.setText("");
    jlosenord.setText("");
    javdelning.setText("");
    textaid.setText("");    
    }
 private String generateRandomPassword(int length) {
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%^&*()-_+=";
    StringBuilder password = new StringBuilder();
    for (int i = 0; i < length; i++) {
        int randomIndex = (int) (Math.random() * chars.length());
        password.append(chars.charAt(randomIndex));
    }
    return password.toString();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textaid = new javax.swing.JTextField();
        javdelning = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        janstallningsdatum = new javax.swing.JTextField();
        jadress = new javax.swing.JTextField();
        jtelefon = new javax.swing.JTextField();
        jefternamn = new javax.swing.JTextField();
        jfornamn = new javax.swing.JTextField();
        GenereraAid = new javax.swing.JButton();
        GenereraLosen = new javax.swing.JButton();
        jlosenord = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lägg till Anställd");

        jLabel2.setText("Förnamn");

        jLabel3.setText("Efternamn");

        jLabel5.setText("Telefon");

        jLabel6.setText("Adress");

        jLabel7.setText("Anställningsdatum");

        jLabel9.setText("Email");

        jLabel10.setText("Avdelning");

        jLabel12.setText("AID:");

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });

        janstallningsdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janstallningsdatumActionPerformed(evt);
            }
        });

        jadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadressActionPerformed(evt);
            }
        });

        jtelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtelefonActionPerformed(evt);
            }
        });

        jfornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfornamnActionPerformed(evt);
            }
        });

        GenereraAid.setText("Generera");
        GenereraAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenereraAidActionPerformed(evt);
            }
        });

        GenereraLosen.setText("Generera");
        GenereraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenereraLosenActionPerformed(evt);
            }
        });

        jlosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlosenordActionPerformed(evt);
            }
        });

        jLabel13.setText("Lösenord");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Spara & Avsluta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8))
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jfornamn)
                                            .addComponent(jefternamn)
                                            .addComponent(jadress)
                                            .addComponent(jtelefon)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(javdelning)
                                            .addComponent(jemail)
                                            .addComponent(janstallningsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlosenord)
                                    .addComponent(textaid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenereraAid)
                                    .addComponent(GenereraLosen))
                                .addGap(25, 25, 25))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(janstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4))
                            .addComponent(javdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenereraAid)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenereraLosen)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfornamnActionPerformed

    private void jtelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtelefonActionPerformed

    private void jadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadressActionPerformed

    private void janstallningsdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janstallningsdatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_janstallningsdatumActionPerformed

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void GenereraAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenereraAidActionPerformed
try {
        String query = "SELECT MAX(aid) FROM anstalld";
        String maxAID = idb.fetchSingle(query);
        int newAID = (maxAID != null) ? Integer.parseInt(maxAID) + 1 : 1;
         textaid.setText(String.valueOf(newAID));

    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Det gick ej att generera: " + e.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_GenereraAidActionPerformed

    private void jlosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlosenordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jlosenord.setEditable(false);
        
        try {
        

        String fornamn = jfornamn.getText().trim();
        String efternamn = jefternamn.getText().trim();
        String adress = jadress.getText().trim();
        String email = jemail.getText().trim();
        String telefon = jtelefon.getText().trim();
        String anstallningsdatum = janstallningsdatum.getText().trim();
        String losenord = jlosenord.getText().trim();
        String avdelning = javdelning.getText().trim();
        String AID = textaid.getText().trim();
        
        
String insertQuery = "INSERT INTO anstalld (fornamn, efternamn, adress, epost, telefon, anstallningsdatum, losenord, aid, avdelning) " +
                             "VALUES ('" + fornamn + "', '" + efternamn + "', '" + adress + "', '" + email + "', '" + 
                             telefon + "', '" + anstallningsdatum + "', '" + losenord + "', '" + AID + "', '" + avdelning + "')";
idb.insert(insertQuery);
 javax.swing.JOptionPane.showMessageDialog(this, "Personen har lagts till i databasen!");

        

    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid databasoperation: " + e.getMessage());
        e.printStackTrace();
    }                                      
        Meny menyInfoFrame = new Meny(idb, aid);
        menyInfoFrame.setVisible(true);   
        this.dispose();
    



            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GenereraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenereraLosenActionPerformed
    String generatedPassword = generateRandomPassword(8); 
    jlosenord.setText(generatedPassword);
    javax.swing.JOptionPane.showMessageDialog(this, "Ett lösenord har genererats och fyllts i!");        
// TODO add your handling code here:
    }//GEN-LAST:event_GenereraLosenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenereraAid;
    private javax.swing.JButton GenereraLosen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jadress;
    private javax.swing.JTextField janstallningsdatum;
    private javax.swing.JTextField javdelning;
    private javax.swing.JTextField jefternamn;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfornamn;
    private javax.swing.JTextField jlosenord;
    private javax.swing.JTextField jtelefon;
    private javax.swing.JTextField textaid;
    // End of variables declaration//GEN-END:variables
} 
