/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author lukas
 */
public class SePartnerHandlaggare extends javax.swing.JFrame {

    private String aid;
    private InfDB idb;
    /**
     * Creates new form SePartnerHandlaggare
     */
    public SePartnerHandlaggare(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
       initComponents();
       visaPartnersIProjekt();
    }


    private void visaPartnersIProjekt() {
        try {
            String sql = "SELECT pa.partner_id, pa.namn, pa.kontaktperson, pa.epost, pa.telefon " +
                         "FROM partner pa " +
                         "JOIN partner_proj pp ON pa.partner_id = pp.partner_id " +
                         "JOIN projekt p ON pp.pid = p.pid " +
                         "JOIN ans_proj ap ON p.pid = ap.pid " +
                         "WHERE ap.aid = '" + aid + "'";
            
            ArrayList<HashMap<String, String>> partners = idb.fetchRows(sql);

            DefaultTableModel modell = (DefaultTableModel) tblPartner.getModel();
            modell.setRowCount(0);

            if (partners != null) {
                for (HashMap<String, String> rad : partners) {
                    String pid = rad.get("PARTNER_ID");
                    String namn = rad.get("NAMN");
                    String kontakt = rad.get("KONTAKTPERSON");
                    String epost = rad.get("EPOST");
                    String telefon = rad.get("TELEFON");

                    Object[] radData = { pid, namn, kontakt, epost, telefon };
                    modell.addRow(radData);
                }
            }
        } catch (InfException e) {
            System.err.println("Fel vid hämtning av partnerdata: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartner = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Partnerinformation för mina projekt");

        tblPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Partner-ID ", "Namn", "Kontaktperson", "E-post ", "Telefon"
            }
        ));
        jScrollPane1.setViewportView(tblPartner);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartner;
    // End of variables declaration//GEN-END:variables
}
