/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author lukas
 */
public class SeProjektHandlaggare extends javax.swing.JFrame {
private String aid;
private InfDB idb;

    /**
     * Creates new form SeProjektHandlaggare
     */
    public SeProjektHandlaggare(InfDB idb, String aid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        visaProjektForHandlaggare();
    }

    private void visaProjektForHandlaggare() {
        try {
            String sql = "SELECT p.pid, p.projektnamn, p.startdatum, p.slutdatum, p.status " +
                         "FROM projekt p JOIN ans_proj ap ON p.pid = ap.pid " +
                         "WHERE ap.aid = " + aid + "";
            
            ArrayList<HashMap<String, String>> projekt = idb.fetchRows(sql);

            DefaultTableModel modell = (DefaultTableModel) tblProjekt.getModel();
            modell.setRowCount(0);
            
            if (projekt != null) {
                for (HashMap<String, String> rad : projekt) {
                    String pid = rad.get("pid");
                    String namn = rad.get("projektnamn");
                    String start = rad.get("startdatum");
                    String slut = rad.get("slutdatum");
                    String status = rad.get("status");
                    
                    Object[] radData = { pid, namn, start, slut, status };
                    modell.addRow(radData);
                    }
            }
            
            int funnaProjekt = projekt.size();
            if (funnaProjekt <= 0)
            {
                JOptionPane.showMessageDialog(null, "Inga projekt funna!");
            }
        } catch (InfException e) {
            System.err.println("Fel vid hämtning av projekt: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjekt = new javax.swing.JTable();
        jButtonTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mina Projekt");

        tblProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PID", "Namn", "Startdatum", "Slutdatum", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblProjekt);

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTillbaka)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButtonTillbaka)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonTillbakaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProjekt;
    // End of variables declaration//GEN-END:variables
}
