/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 * ÄNDRA TEXTBOX STORLEKT BLIR AUTOMATISKT SMÅ &&!!
 * @author viktor
 */
public class SkapaNyttLand extends javax.swing.JFrame {
    private InfDB idb;
    private String aid;

    /**
     * Creates new form SkapaNyttLand
     */
    public SkapaNyttLand(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
    }
private void sparaNyttLand() {
    try {
      // Get values ​​from the text fields
            String lid = jTextLandID.getText().trim();
            String namn = jTextNamn.getText().trim();
            String sprak = jTextSprak.getText().trim();
            String valuta = jTextValuta.getText().trim();
            String tidsZon = jTextTidsZon.getText().trim();
            String politiskStruktur = jTextPS.getText().trim();
            String ekonomi = jTextEkonomi.getText().trim();

            // Validate that no fields are empty
            if (!Validering.textFaltHarVarde(jTextLandID) || !Validering.textFaltHarVarde(jTextNamn) || !Validering.textFaltHarVarde(jTextSprak) || !Validering.textFaltHarVarde(jTextValuta) ||
                !Validering.textFaltHarVarde(jTextTidsZon) || !Validering.textFaltHarVarde(jTextPS) || !Validering.textFaltHarVarde(jTextEkonomi)) {
                return;  
    }
                // Check if LID already exists
            String existingLid = idb.fetchSingle("SELECT lid FROM land WHERE lid = '" + lid + "'");
            if (existingLid != null) {
                JOptionPane.showMessageDialog(this, "Ett land med detta LID finns redan!");
                return;
            }

            
            // Create the SQL INSERT query
            String insertQuery = String.format(
                "INSERT INTO land (lid, namn, sprak, valuta, tidszon, politisk_struktur, ekonomi) " +
                "VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')",
                lid, namn, sprak, valuta, tidsZon, politiskStruktur, ekonomi
            );
             // Execute the INSERT query
            idb.insert(insertQuery);

            
            // Bekräftelsemeddelande
            JOptionPane.showMessageDialog(this, "Landet har lagts till!");

            
            // Töm textfält
            clearForm();
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid sparande av land: " + e.getMessage());
        }
}
//* skapa och tömma textfält för när användare lägger till land
private void clearForm() {
        jTextLandID.setText("");
        jTextNamn.setText("");
        jTextSprak.setText("");
        jTextValuta.setText("");
        jTextTidsZon.setText("");
        jTextPS.setText("");
        jTextEkonomi.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextLandID = new javax.swing.JTextField();
        jTextNamn = new javax.swing.JTextField();
        jTextSprak = new javax.swing.JTextField();
        jTextValuta = new javax.swing.JTextField();
        jTextTidsZon = new javax.swing.JTextField();
        jTextPS = new javax.swing.JTextField();
        jTextEkonomi = new javax.swing.JTextField();
        jButtonSpara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextLandID.setText("  ");

        jButtonSpara.setText("Spara");
        jButtonSpara.setActionCommand("Spara");
        jButtonSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSparaActionPerformed(evt);
            }
        });

        jLabel1.setText("Land-ID");

        jLabel2.setText("Namn");

        jLabel3.setText("Språk");

        jLabel4.setText("Valuta");

        jLabel5.setText("Tidszon");

        jLabel6.setText("Politisk struktur");

        jLabel7.setText("Ekonomi");

        jLabel8.setText("Skapa nytt land");

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSpara)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonTillbaka)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextTidsZon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextLandID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(176, 176, 176))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTidsZon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSpara)
                    .addComponent(jButtonTillbaka))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSparaActionPerformed
    sparaNyttLand(); 
    }//GEN-LAST:event_jButtonSparaActionPerformed

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTillbakaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSpara;
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextEkonomi;
    private javax.swing.JTextField jTextLandID;
    private javax.swing.JTextField jTextNamn;
    private javax.swing.JTextField jTextPS;
    private javax.swing.JTextField jTextSprak;
    private javax.swing.JTextField jTextTidsZon;
    private javax.swing.JTextField jTextValuta;
    // End of variables declaration//GEN-END:variables
}
