/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;

import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author nicklas
 */
public class AdminProjekt extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String pid;
    /**
     * Creates new form AdminProjekt
     */
    public AdminProjekt(InfDB idb, String aid) {
        
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.pid = pid;
        PopuleraTabellProjekt();
    }
    
    
    private void PopuleraTabellProjekt() {
        try {
            String sql = "SELECT pid, projektnamn, beskrivning, startdatum, "
                    + "slutdatum, kostnad, status, prioritet, projektchef, land FROM projekt";
            ArrayList<HashMap<String, String>> projektLista = idb.fetchRows(sql);

            String[] kolumner = {"PID", "Namn", "Beskrivning", "Startdatum", "Slutdatum",
                "Kostnad", "Status", "Prioritet", "Projektchef", "Land"};

            DefaultTableModel modell = new DefaultTableModel(kolumner, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };   
            for (HashMap<String, String> p : projektLista) {
                modell.addRow(new Object[]{
                p.get("pid"), p.get("projektnamn"), p.get("beskrivning"),
                p.get("startdatum"), p.get("slutdatum"), p.get("kostnad"),
                p.get("status"), p.get("prioritet"),
                p.get("projektchef"), p.get("land")
                });
            }
            
            jTableProjekt.setModel(modell);
            
        }   catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTillbaka = new javax.swing.JButton();
        jButtonRedigera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        jButtonRedigera.setText("Redigera");
        jButtonRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedigeraActionPerformed(evt);
            }
        });

        jTableProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProjekt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableProjekt.setColumnSelectionAllowed(false);
        jTableProjekt.setFillsViewportHeight(true);
        jTableProjekt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableProjekt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRedigera)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTillbaka)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTillbaka)
                    .addComponent(jButtonRedigera))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedigeraActionPerformed
        int valdRad = jTableProjekt.getSelectedRow();
        
       
        if (valdRad == -1){
            JOptionPane.showMessageDialog(null, "Välj ett projekt i listan först!");
            return;
        }
        
        this.pid = jTableProjekt.getValueAt(valdRad, 0).toString();
        new RedigeraProjekt(idb, pid).setVisible(true);
    }//GEN-LAST:event_jButtonRedigeraActionPerformed

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRedigera;
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjekt;
    // End of variables declaration//GEN-END:variables
}
