/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;

import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author nicklas
 */
public class Meny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;
    private Validering validering;
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String aid) {
        try {
            initComponents();
            this.idb = idb;
            this.aid = aid;
            this.validering = new Validering(idb);
            
            String roll = validering.hamtaRoll(aid);
            switch (roll.toLowerCase()){
                case "admin":
                    break;
                case "projektchef":
                    //btnEditInfo.setVisible(false);
                    break;
                case "handlaggare":
                    //
                    break;
                case "anställd":
                default:
                    //
                    break;
            }
            
            jLabelLoggedInUser.setText("Inloggad som: " + validering.hamtaRoll(aid));
        } catch (InfException ex) {
            Logger.getLogger(Meny.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLoggedInUser = new javax.swing.JLabel();
        jSkapaNyttLandBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        VisaAvdelningsProjektbtn = new javax.swing.JButton();
        jButtonAdminProjekt = new javax.swing.JButton();
        jButtonAnvandarInformation = new javax.swing.JButton();
        jButtonLaggTillAnstalld = new javax.swing.JButton();
        jButtonTaBortAnvandare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLoggedInUser.setText("jLabel1");

        jSkapaNyttLandBtn.setText("Skapa nytt land");
        jSkapaNyttLandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSkapaNyttLandBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Lägg till partner");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VisaAvdelningsProjektbtn.setText("Visa avdelningens projekt");
        VisaAvdelningsProjektbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaAvdelningsProjektbtnActionPerformed(evt);
            }
        });

        jButtonAdminProjekt.setText("AdminProjekt");
        jButtonAdminProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminProjektActionPerformed(evt);
            }
        });

        jButtonAnvandarInformation.setText("Användarinformation");
        jButtonAnvandarInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnvandarInformationActionPerformed(evt);
            }
        });

        jButtonLaggTillAnstalld.setText("Lägg till anställd");
        jButtonLaggTillAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaggTillAnstalldActionPerformed(evt);
            }
        });

        jButtonTaBortAnvandare.setText("Ta bort användare");
        jButtonTaBortAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaBortAnvandareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLoggedInUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonLaggTillAnstalld))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSkapaNyttLandBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VisaAvdelningsProjektbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonAdminProjekt))
                            .addComponent(jButtonAnvandarInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addComponent(jButtonTaBortAnvandare)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoggedInUser)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSkapaNyttLandBtn)
                    .addComponent(jButtonTaBortAnvandare))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(VisaAvdelningsProjektbtn)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdminProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAnvandarInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLaggTillAnstalld)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSkapaNyttLandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSkapaNyttLandBtnActionPerformed
        new SkapaNyttLand(idb, aid).setVisible(true);
    }//GEN-LAST:event_jSkapaNyttLandBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LaggTillPartner(idb, aid).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VisaAvdelningsProjektbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaAvdelningsProjektbtnActionPerformed
        new VisaAvdelningsProjekt(idb, aid).setVisible(true);
    }//GEN-LAST:event_VisaAvdelningsProjektbtnActionPerformed

    private void jButtonAdminProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminProjektActionPerformed
        new AdminProjekt(idb, aid).setVisible(true);
    }//GEN-LAST:event_jButtonAdminProjektActionPerformed

    private void jButtonAnvandarInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnvandarInformationActionPerformed
        new AnvandarInformation(idb, aid).setVisible(true);
    }//GEN-LAST:event_jButtonAnvandarInformationActionPerformed

    private void jButtonLaggTillAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaggTillAnstalldActionPerformed
        new LaggTillAnstalld(idb, aid).setVisible(true);
    }//GEN-LAST:event_jButtonLaggTillAnstalldActionPerformed

    private void jButtonTaBortAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaBortAnvandareActionPerformed
       new TaBortAnvandare(idb, aid).setVisible(true);
    }//GEN-LAST:event_jButtonTaBortAnvandareActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisaAvdelningsProjektbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdminProjekt;
    private javax.swing.JButton jButtonAnvandarInformation;
    private javax.swing.JButton jButtonLaggTillAnstalld;
    private javax.swing.JButton jButtonTaBortAnvandare;
    private javax.swing.JLabel jLabelLoggedInUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSkapaNyttLandBtn;
    // End of variables declaration//GEN-END:variables
}
