/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author nicklas
 */
public class SkapaNyttProjekt extends javax.swing.JFrame {

    private InfDB idb;
    private String pid;
    private Validering validering;
    HashMap<String, String> projektchefNamnTillID = new HashMap<>();
    HashMap<String, String> landNamnTillID = new HashMap<>();
    /**
     * Creates new form LaggTillProjekt
     */
    public SkapaNyttProjekt(InfDB idb) {
        this.idb = idb;
        initComponents();
        this.pid = pid;
        this.validering = new Validering(idb);
        fyllFalt();
        
    }

    private void fyllFalt() {
        try {
            String sqlHandlaggare = "SELECT h.aid, a.fornamn, a.efternamn FROM handlaggare h JOIN anstalld a ON h.aid = a.aid";
            
            String nyttPID = idb.getAutoIncrement("projekt", "pid");
            txtPID.setText(nyttPID);
            txtPID.setEditable(false);
            
            var result1 = idb.fetchRows(sqlHandlaggare);
            for (var rad : result1) {
                String id = rad.get("aid");
                String namn = rad.get("fornamn") + " " + rad.get("efternamn");
                jComboBoxProjektChef.addItem(namn);
                projektchefNamnTillID.put(namn, id);
            }

                // Länder
                String sqlLand = "SELECT lid, namn FROM land";
                var result2 = idb.fetchRows(sqlLand);
                for (var rad : result2) {
                    String id = rad.get("lid");
                    String namn = rad.get("namn");
                    jComboBoxLand.addItem(namn);
                    landNamnTillID.put(namn, id);
                }
            } catch (InfException e) {
            e.printStackTrace();
            }
        }
    
    private void sparaNyttProjekt() {//throws InfException{
        
        String pid = txtPID.getText();
        String projektnamn = txtProjektNamn.getText().trim();
        String beskrivning = txtBeskrivning.getText().trim();
        String startdatum = jFormattedTextFieldStartDatum.getText().trim();
        String slutdatum = jFormattedTextFieldStartDatum.getText().trim();
        String kostnad = txtKostnad.getText().trim();
        
        String status = jComboBoxStatus.getSelectedItem().toString();
        String prioritet = jComboBoxPrioritet.getSelectedItem().toString();
        
        String valtNamnChef = jComboBoxProjektChef.getSelectedItem().toString();
        String projektchefID = projektchefNamnTillID.get(valtNamnChef);
        
        String valtLand = jComboBoxLand.getSelectedItem().toString();
        String landID =  landNamnTillID.get(valtLand);
        
        JOptionPane.showMessageDialog(null, "Ett nytt projekt har skapats!");
        JOptionPane.showMessageDialog(null, pid + projektnamn + beskrivning + startdatum + slutdatum + kostnad + status + prioritet + valtNamnChef + projektchefID + valtLand + landID);
        
        String insertQuery = "INSERT INTO projekt (pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, status, prioritet, projektchef, land) " +
                             "VALUES ('" + pid + "', '" + projektnamn + "', '" + beskrivning + "', '" + startdatum + "', '" + 
                             slutdatum + "', '" + kostnad + "', '" + status + "', '" + prioritet + "', '" + projektchefID + "', '" + landID + "')";
        try {
            idb.insert(insertQuery);
        } catch (InfException ex) {
            Logger.getLogger(SkapaNyttProjekt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelProjektNamn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStartDatum = new javax.swing.JLabel();
        jLabelSlutDatum = new javax.swing.JLabel();
        jLabelKostnad = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelPrioritet = new javax.swing.JLabel();
        jLabelProjektchef = new javax.swing.JLabel();
        jLabelLand = new javax.swing.JLabel();
        txtProjektNamn = new javax.swing.JTextField();
        txtBeskrivning = new javax.swing.JTextField();
        txtKostnad = new javax.swing.JTextField();
        jButtonTillbaka = new javax.swing.JButton();
        jFormattedTextFieldStartDatum = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSlutDatum = new javax.swing.JFormattedTextField();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxPrioritet = new javax.swing.JComboBox<>();
        jButtonSparaOchAvsluta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        jComboBoxProjektChef = new javax.swing.JComboBox<>();
        jComboBoxLand = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skapa nytt projekt");

        jLabelProjektNamn.setText("Projektnamn");

        jLabel3.setText("Beskrivning");

        jLabelStartDatum.setText("Startdatum");

        jLabelSlutDatum.setText("Slutdatum");

        jLabelKostnad.setText("Kostnad");

        jLabelStatus.setText("Status");

        jLabelPrioritet.setText("Prioritet");

        jLabelProjektchef.setText("Projektchef");

        jLabelLand.setText("Land");

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        jFormattedTextFieldStartDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jFormattedTextFieldSlutDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planerat", "Pågående", "Avslutat", "" }));

        jComboBoxPrioritet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Låg", "Medel", "Hög" }));

        jButtonSparaOchAvsluta.setText("Spara & avsluta");
        jButtonSparaOchAvsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSparaOchAvslutaActionPerformed(evt);
            }
        });

        jLabel2.setText("ProjektID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTillbaka)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelStartDatum)
                    .addComponent(jLabelSlutDatum)
                    .addComponent(jLabelKostnad)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelPrioritet)
                    .addComponent(jLabelProjektchef)
                    .addComponent(jLabelLand)
                    .addComponent(jLabelProjektNamn))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxStatus, 0, 127, Short.MAX_VALUE)
                            .addComponent(jComboBoxPrioritet, 0, 127, Short.MAX_VALUE)
                            .addComponent(jComboBoxLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jButtonSparaOchAvsluta)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtProjektNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtBeskrivning, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKostnad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldSlutDatum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxProjektChef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldStartDatum, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProjektNamn)
                    .addComponent(txtProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStartDatum)
                    .addComponent(jFormattedTextFieldStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSlutDatum)
                    .addComponent(jFormattedTextFieldSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKostnad)
                    .addComponent(txtKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrioritet)
                    .addComponent(jComboBoxPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProjektchef)
                    .addComponent(jComboBoxProjektChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLand)
                    .addComponent(jComboBoxLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTillbaka)
                    .addComponent(jButtonSparaOchAvsluta))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSparaOchAvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSparaOchAvslutaActionPerformed
        sparaNyttProjekt();
        this.dispose();
    }//GEN-LAST:event_jButtonSparaOchAvslutaActionPerformed

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSparaOchAvsluta;
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JComboBox<String> jComboBoxLand;
    private javax.swing.JComboBox<String> jComboBoxPrioritet;
    private javax.swing.JComboBox<String> jComboBoxProjektChef;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JFormattedTextField jFormattedTextFieldSlutDatum;
    private javax.swing.JFormattedTextField jFormattedTextFieldStartDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelKostnad;
    private javax.swing.JLabel jLabelLand;
    private javax.swing.JLabel jLabelPrioritet;
    private javax.swing.JLabel jLabelProjektNamn;
    private javax.swing.JLabel jLabelProjektchef;
    private javax.swing.JLabel jLabelSlutDatum;
    private javax.swing.JLabel jLabelStartDatum;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JTextField txtBeskrivning;
    private javax.swing.JTextField txtKostnad;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtProjektNamn;
    // End of variables declaration//GEN-END:variables
}
