package SDGSweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
/**
 *
 * @author fredde
 */
public class TaBortAnvandare extends javax.swing.JFrame {
        private InfDB idb;
        private String aid;
    /**
     * Creates new form TaBortAnvandare
     */
    public TaBortAnvandare(InfDB idb, String aid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        staffComboBox();
    }
    private void staffComboBox() {
        try {
            String query ="SELECT aid, fornamn, efternamn FROM anstalld";
            ArrayList<HashMap<String, String>> users = idb.fetchRows(query);
            
            if (users != null) {
                for (HashMap<String, String> user : users){
                    String name = user.get("aid") + ". " + user.get("fornamn") + " " + user.get("efternamn");
                    jComboBox1.addItem(name);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Inga användare hittades i systemet.");
            }
            
        } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning av användare: " + e.getMessage());
        e.printStackTrace();
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ta bort Användare");
        jLabel1.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ta bort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String selectedUser= (String) jComboBox1.getSelectedItem();
        
        if (selectedUser != null && !selectedUser.isEmpty()) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Är du säker på att du vill ta bort " + selectedUser + " från systemet?",
            "Bekräfta borttagning",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_NO_OPTION) {
            deleteUser(selectedUser);
        }
      }  else {
            javax.swing.JOptionPane.showMessageDialog(this, "Välj en användare att ta bort.");
        }
            // Säkerställer att användare vill ta bort projektet.
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
private void deleteUser(String selectedUser) {
        try {
            String[] parts = selectedUser.split(" ");
            String fornamn = parts[0];
            String efternamn = parts[1];

            String deleteQuery = "DELETE FROM anstalld WHERE fornamn = '" + fornamn + "' AND efternamn = '" + efternamn + "'";
            idb.delete(deleteQuery);

            javax.swing.JOptionPane.showMessageDialog(this, selectedUser + " har tagits bort från systemet.");
            jComboBox1.removeItem(selectedUser);
        } catch (InfException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fel vid borttagning av användare: " + e.getMessage());
            e.printStackTrace();
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
