/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author lukas
 */
public class VisaAvdelningsProjekt extends javax.swing.JFrame {
private InfDB idb;
private String aid;

    /**
     * Creates new form VisaAvdelningsProjekt
     */
    public VisaAvdelningsProjekt(InfDB idb,String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        populeraTabellAvdelning();
    } 
    
    
private void populeraTabellAvdelning()
{
    try {    
        String sqlFraga = 
            "SELECT projekt.pid, projekt.projektnamn, projekt.beskrivning, projekt.startdatum, " +
            "projekt.slutdatum, projekt.kostnad, projekt.status, projekt.prioritet, projekt.land " +
            "FROM projekt " +
            "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
            "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
            "WHERE anstalld.avdelning = (SELECT avdelning FROM anstalld WHERE aid = '" + aid + "') ";

        ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

        DefaultTableModel modell = (DefaultTableModel) jTblProjects.getModel();
        modell.setRowCount(0); // Rensar tabellen först
        javax.swing.JOptionPane.showMessageDialog(this, aid);
        for (HashMap<String, String> rad : resultat) {
            modell.addRow(new Object[] {
                rad.get("pid"),
                rad.get("projektnamn"),
                rad.get("beskrivning"),
                rad.get("startdatum"),
                rad.get("slutdatum"),
                rad.get("kostnad"),
                rad.get("status"),
                rad.get("prioritet"),
                rad.get("land")
            });
        }
    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + e.getMessage());
    }
}
private void visaProjektPerStatus() {
    try {
        String valdStatus = jComboBox2.getSelectedItem().toString();

        String sqlFraga = 
            "SELECT projekt.pid, projekt.projektnamn, projekt.beskrivning, projekt.startdatum, " +
            "projekt.slutdatum, projekt.kostnad, projekt.status, projekt.prioritet, projekt.land " +
            "FROM projekt " +
            "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
            "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
            "WHERE anstalld.avdelning = (SELECT avdelning FROM anstalld WHERE aid = '" + aid + "')";
        
        if (!valdStatus.equals("Alla")){
           sqlFraga += "AND projekt.status = '" + valdStatus + "'";
        }
            

        ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

        DefaultTableModel modell = (DefaultTableModel) jTblProjects.getModel();
        modell.setRowCount(0); // Rensar tabellen först

        for (HashMap<String, String> rad : resultat) {
            modell.addRow(new Object[] {
                rad.get("pid"),
                rad.get("projektnamn"),
                rad.get("beskrivning"),
                rad.get("startdatum"),
                rad.get("slutdatum"),
                rad.get("kostnad"),
                rad.get("status"),
                rad.get("prioritet"),
                rad.get("land")
            });
        }
    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProjects = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButtonTillbaka = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pid", "projektnamn", "beskrivning", "startdatum", "slutdatum", "kostnad", "status", "prioritet", "land"
            }
        ));
        jScrollPane1.setViewportView(jTblProjects);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alla", "Planerat", "Pågående", "Avslutat", " " }));

        jButton1.setText("Visa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTillbaka)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButtonTillbaka))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        visaProjektPerStatus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblProjects;
    // End of variables declaration//GEN-END:variables
}

